include ../buildTools/config.mk
MAKEEXE := 1
include ../buildTools/BasicMakefile
INCLUDEFLAGS += -std=c++11 -I/home/daq/msgpack/include -I/home/daq/src/AutobahnCpp
LIBFLAGS += -L/usr/local/universe/lib -L"/home_nowrite/CDT Ware/Software/HardwareLib_5.1" -lHardwareLib -luniverse_api -lboost_system -lboost_thread -lpthread
